// Run with Playwright MCP against the isolated synthetic fixture on loopback.
async (page) => {
  const origin='http://127.0.0.1:8867';
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error') errors.push(message.text());});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(origin+'/network/hosts?status=all&seen_within=all&page=2&limit=100');
  if(page.url().includes('/login')) {
    await page.getByRole('textbox',{name:'Логин',exact:true}).fill('synthetic');
    await page.getByRole('textbox',{name:'Пароль',exact:true}).fill('synthetic-browser-only');
    await page.getByRole('button',{name:'Войти',exact:true}).click();
    await page.goto(origin+'/network/hosts?status=all&seen_within=all&page=2&limit=100');
  }
  const row=page.locator('[data-hosts-rows] tr').filter({hasText:'192.0.2.124'});
  await row.getByRole('link',{name:'Открыть',exact:true}).click();
  const back=page.getByRole('link',{name:'Назад к списку',exact:true});
  if(!(await back.getAttribute('href')).includes('page=2')) throw Error('Card lost page');
  if(await page.locator('nav a[aria-current=page]').innerText()!=='Устройства сети') throw Error('Card active menu wrong');
  await back.click();
  if(!page.url().includes('page=2')) throw Error('Back lost page');
  await page.goBack(); await page.goForward();
  if(!page.url().includes('page=2')) throw Error('History lost page');
  await page.getByRole('button',{name:'Диагностический',exact:true}).click();
  const diagnostic=await page.locator('[data-network-hosts] th:visible').count();
  await page.reload();
  if(await page.locator('[data-network-hosts]').getAttribute('data-table-mode')!=='diagnostic') throw Error('Mode not retained');
  await page.getByRole('button',{name:'Краткий',exact:true}).click();
  const brief=await page.locator('[data-network-hosts] th:visible').count();
  if(diagnostic!==15||brief!==7) throw Error('Wrong column modes');
  await page.getByRole('textbox',{name:'Поиск по IP, MAC, имени',exact:true}).fill('DO_NOT_STORE_search');
  await page.getByRole('combobox',{name:'На странице',exact:true}).selectOption('25');
  await page.getByRole('textbox',{name:'Название представления',exact:true}).fill('Synthetic saved view');
  await page.getByRole('button',{name:'Сохранить фильтры',exact:true}).click();
  const stored=await page.evaluate(()=>localStorage.getItem('panel.host-views.v1.1'));
  if(stored.includes('DO_NOT_STORE')||stored.includes('"q"')) throw Error('Search saved');
  await page.getByRole('button',{name:'Применить',exact:true}).click();
  await page.waitForLoadState('networkidle');
  if(!page.url().includes('page=1')||!page.url().includes('limit=25')) throw Error('View not applied');
  await page.getByRole('combobox',{name:'Сохранённое представление',exact:true}).selectOption('0');
  await page.getByRole('button',{name:'Удалить представление',exact:true}).click();
  if(await page.getByRole('combobox',{name:'Сохранённое представление',exact:true}).locator('option').count()!==1) throw Error('Delete failed');
  const labels=async()=> (await page.locator('[data-hosts-rows] tr td:nth-child(6)').allTextContents()).map(value=>value.trim());
  const before=await labels();
  const payload=await page.evaluate(async()=>{const r=await fetch('/api/v1/network/hosts'+location.search);return r.json();});
  await page.route('**/api/v1/network/hosts/meta',async route=>{const r=await route.fetch();const json=await r.json();json.data.snapshot.snapshot_id=2;await route.fulfill({json});});
  await page.route('**/api/v1/network/hosts?*',async route=>{payload.data.snapshot.snapshot_id=2;await route.fulfill({json:payload});});
  await page.waitForFunction(()=>document.querySelector('[data-network-hosts]')?.dataset.snapshotId==='2',{},{timeout:25000});
  const after=await labels();
  if(JSON.stringify(before)!==JSON.stringify(after)) throw Error('Status parity failed');
  if(!(await page.locator('[data-hosts-rows] tr').filter({hasText:'192.0.2.24'}).locator('.actions a').getAttribute('href')).includes('return_url=')) throw Error('Dynamic return missing');
  await page.unrouteAll({behavior:'ignoreErrors'});
  await page.screenshot({path:'C:/Users/admin-2/.codex/worktrees/panel-jobs/ui_vpn/output/playwright/panel-navigation/desktop-final.png'});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Открыть меню',exact:true}).focus();
  await page.keyboard.press('Enter');
  if(!(await page.locator('main').evaluate(node=>node.inert))) throw Error('Background focus not blocked');
  await page.locator('#primary-navigation details').last().locator('summary').focus();
  await page.keyboard.press('Tab');
  if(await page.locator('.mobile-nav-toggle').evaluate(node=>node!==document.activeElement)) throw Error('Mobile focus escaped');
  await page.keyboard.press('Escape');
  if(await page.locator('.mobile-nav-toggle').getAttribute('aria-expanded')!=='false') throw Error('Escape failed');
  if(await page.locator('main').evaluate(node=>node.inert)) throw Error('Background remained blocked');
  await page.getByRole('button',{name:'Диагностический',exact:true}).focus();
  await page.keyboard.press('Enter');
  if(await page.locator('[data-network-hosts]').getAttribute('data-table-mode')!=='diagnostic') throw Error('Keyboard mode failed');
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
  if(overflow) throw Error('Mobile body overflow');
  await page.getByRole('button',{name:'Краткий',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#primary-navigation').getBoundingClientRect().right<=1);
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'C:/Users/admin-2/.codex/worktrees/panel-jobs/ui_vpn/output/playwright/panel-navigation/mobile-final.png'});
  await page.locator('[data-hosts-rows] tr').filter({hasText:'192.0.2.24'}).getByRole('link',{name:'Открыть',exact:true}).click();
  if(!(await page.title()).includes('Synthetic browser device')) throw Error('Mobile card action failed');
  await page.getByRole('link',{name:'Назад к списку',exact:true}).click();
  const blocked=await page.context().newPage();
  blocked.on('pageerror',error=>errors.push(error.message));
  await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}}));
  await blocked.goto(origin+'/network/hosts?status=all&seen_within=all&limit=25');
  await blocked.getByRole('button',{name:'Диагностический',exact:true}).click();
  if(await blocked.locator('[data-network-hosts]').getAttribute('data-table-mode')!=='diagnostic') throw Error('Blocked storage broke mode');
  if(!(await blocked.locator('[data-view-feedback]').innerText()).includes('не разрешает')) throw Error('Missing storage feedback');
  await blocked.close();
  if(errors.length) throw Error('Console: '+errors.join(';'));
  return {cardBackPage:2,history:true,modes:{diagnostic,brief},savedViews:true,searchExcluded:true,
    statuses:before.slice(0,6),dynamicParity:true,mobile:true,keyboard:true,mobileCardAction:true,blockedStorage:true,bodyOverflow:overflow,consoleErrors:errors.length};
};
