---
- name: Enable automatic home creation for SSSD domain users
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth-sss-only
    regexp: '^session[[:space:]]+required[[:space:]]+pam_mkhomedir\.so.*$'
    line: 'session required pam_mkhomedir.so skel=/etc/skel umask=0077'
    owner: root
    group: root
    mode: "0644"

- name: Verify automatic home creation for SSSD domain users
  ansible.builtin.command:
    argv:
      - grep
      - -Fx
      - 'session required pam_mkhomedir.so skel=/etc/skel umask=0077'
      - /etc/pam.d/system-auth-sss-only
  changed_when: false
