---
desktop_shortcuts_skel_dir: /etc/skel/Рабочий стол
desktop_shortcuts_skel_autostart_dir: /etc/skel/.config/autostart
desktop_shortcuts_applications_dir: /usr/share/applications
desktop_shortcuts_application_entries:
  - yandex-browser.desktop
  - onlyoffice-desktopeditors.desktop
  - nextcloud-client.desktop
desktop_shortcuts_nextcloud_entry: nextcloud-client.desktop
